### ISSUE TITLE
Error: Cannot find module 'node:events' (npm installed)

### ISSUE THREAD

**Issue by whxyu1337** [Wumpuspro/Luminious-bot#3]
C:\Users\Administrator\Desktop\Moon>node xp.js
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- C:\Users\Administrator\Desktop\Moon\node_modules\discord.js\src\client\BaseClient.js
- C:\Users\Administrator\Desktop\Moon\node_modules\discord.js\src\index.js
- C:\Users\Administrator\Desktop\Moon\xp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\Moon\node_modules\discord.js\src\client\BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Desktop\\Moon\\node_modules\\discord.js\\src\\client\\BaseClient.js',
    'C:\\Users\\Administrator\\Desktop\\Moon\\node_modules\\discord.js\\src\\index.js',
    'C:\\Users\\Administrator\\Desktop\\Moon\\xp.js'
  ]
}

**Comment by whxyu1337** [comment]
![image](https://user-images.githubusercontent.com/78328022/136660706-71883e2c-7fe4-43ce-8820-9a8fee6a3f0a.png)
Both on replit and my pc

**Comment by whxyu1337** [comment]
fixed
